export default function returnTheme() {

    const temas = ['mi regalo favorito / my favorite gift',
    'mi sentimiento favorito / my favorite feeling',
    'mi viaje favorito / my favorite trip',
    'mi país favorito / my favorite country',
    'mi comida favorita / my favorite food',
    'mi día más feliz / my happiest day',
    'mi recuerdo más preciado / my most cherished memory',
    'mi mayor logro / my greatest achievement',
    'mi mayor desafío / my biggest challenge',
    'mi libro favorito / my favorite book',
    'mi película favorita / my favorite movie',
    'mi serie de televisión favorita / my favorite TV show',
    'mi canción favorita / my favorite song',
    'mi artista favorito / my favorite artist',
    'mi deporte favorito / my favorite sport',
    'mi pasatiempo favorito / my favorite hobby',
    'mi mejor amigo / my best friend',
    'mi relación familiar más cercana / my closest family relationship',
    'mi primer amor / my first love',
    'mi mayor miedo / my biggest fear',
    'mi mayor arrepentimiento / my biggest regret',
    'mi momento más embarazoso / my most embarrassing moment',
    'mi mayor sueño / my biggest dream',
    'mi objetivo de vida / my life goal',
    'mi trabajo ideal / my ideal job',
    'mi primer trabajo / my first job',
    'mi primer día de escuela / my first day of school',
    'mi graduación / my graduation',
    'mi primer viaje solo / my first solo trip',
    'mi mascota favorita / my favorite pet',
    'mi juego de infancia favorito / my favorite childhood game',
    'mi primer recuerdo / my first memory',
    'mi momento más orgulloso / my proudest moment',
    'mi mayor inspiración / my greatest inspiration',
    'mi mayor influencia / my greatest influence',
    'mi habilidad oculta / my hidden skill',
    'mi secreto mejor guardado / my best kept secret',
    'mi lugar seguro / my safe place',
    'mi lugar favorito en el mundo / my favorite place in the world',
    'mi tradición familiar favorita / my favorite family tradition',
    'mi festividad favorita / my favorite holiday',
    'mi estación del año favorita / my favorite season',
    'mi clima favorito / my favorite weather',
    'mi plato casero favorito / my favorite homemade dish',
    'mi bebida favorita / my favorite drink',
    'mi postre favorito / my favorite dessert',
    'mi experiencia culinaria más memorable / my most memorable culinary experience',
    'mi primer concierto / my first concert',
    'mi deportista favorito / my favorite athlete',
    'mi equipo deportivo favorito / my favorite sports team',
    'mi hobby más inusual / my most unusual hobby',
    'mi mayor virtud / my greatest virtue',
    'mi mayor defecto / my greatest flaw',
    'mi experiencia más transformadora / my most transformative experience',
    'mi mayor pérdida / my greatest loss',
    'mi experiencia más aterradora / my scariest experience',
    'mi encuentro más significativo / my most meaningful encounter',
    'mi decisión más difícil / my toughest decision',
    'mi error más grande / my biggest mistake',
    'mi viaje más aventurero / my most adventurous trip',
    'mi ciudad natal / my hometown',
    'mi ciudad favorita / my favorite city',
    'mi país que deseo visitar / the country I wish to visit',
    'mi idioma extranjero favorito / my favorite foreign language',
    'mi obra de arte favorita / my favorite piece of art',
    'mi museo favorito / my favorite museum',
    'mi parque favorito / my favorite park',
    'mi actividad al aire libre favorita / my favorite outdoor activity',
    'mi videojuego favorito / my favorite videogame',
    'mi aplicación móvil favorita / my favorite mobile app',
    'mi red social favorita / my favorite social network',
    'mi tecnología favorita / my favorite technology',
    'mi invento favorito / my favorite invention',
    'mi período histórico favorito / my favorite historical period',
    'mi figura histórica favorita / my favorite historical figure',
    'mi cita favorita / my favorite quote',
    'mi filosofía de vida / my life philosophy',
    'mi mantra personal / my personal mantra',
    'mi estilo de moda favorito / my favorite fashion style',
    'mi prenda de vestir favorita / my favorite piece of clothing',
    'mi accesorio favorito / my favorite accessory',
    'mi marca favorita / my favorite brand',
    'mi tienda favorita / my favorite store',
    'mi compra más significativa / my most significant purchase',
    'mi regalo más inesperado / my most unexpected gift',
    'mi talento más inusual / my most unusual talent',
    'mi momento de mayor aprendizaje / my greatest learning moment',
    'mi libro de autoayuda favorito / my favorite self-help book',
    'mi consejo más valioso / my most valuable advice',
    'mi enseñanza más importante / my most important teaching',
    'mi momento de claridad / my moment of clarity',
    'mi experiencia espiritual más profunda / my deepest spiritual experience',
    'mi práctica de mindfulness favorita / my favorite mindfulness practice',
    'mi ejercicio de relajación favorito / my favorite relaxation exercise',
    'mi rutina de bienestar favorita / my favorite wellness routine',
    'mi hábito más saludable / my healthiest habit',
    'mi indulgencia favorita / my favorite indulgence']
    
    // Lógica de la función
    const RandomTheme = temas[Math.floor(Math.random() * temas.length)];

    return RandomTheme
  }